name: .NET CI (desktop)

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      SLN_PATH: aulas/WinFormsPostgreSqlSolution/WinFormsPostgreSql.sln
      TEST_CSPROJ: aulas/WinFormsPostgreSqlSolution/WinFormsPostgreSql.Tests/WinFormsPostgreSql.Tests.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            7.0.x

      - name: Restore (solution)
        run: dotnet restore "$env:SLN_PATH"

      - name: Build (solution)
        run: dotnet build "$env:SLN_PATH" -c Release --no-restore
     
      - name: Test (solution)
        run: |
          dotnet test "$env:SLN_PATH" -c Release --no-build `
            --logger "trx;LogFileName=solution-tests.trx" `
            --results-directory "$env:RUNNER_TEMP\test-results"
    
      - name: Test (specific test project)
        run: |
          dotnet test "$env:TEST_CSPROJ" -c Release --no-build `
            --logger "trx;LogFileName=project-tests.trx" `
            --results-directory "$env:RUNNER_TEMP\test-results"

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ runner.temp }}/test-results
          if-no-files-found: warn